### ISSUE TITLE
Compiler Crash during mmdetection installation

### ISSUE THREAD

**Issue by ivder** [open-mmlab/mmdetection#1055]
I have followed the installation instruction until this step `python setup.py develop`, then I got the following error, Any help would be appreciated.

```
File "/home/ivan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/ivan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2210, i                                                                                                               n visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/home/ivan/anaconda3/envs/open-mmlab/lib/python                                                                                                               3.7/site-packages/Cython/Includes/numpy/__init__.pxd>, 842, 5), 'AnalyseExpressionsTransform', 'Compiler crash in AnalyseExpre                                                                                                               ssionsTransform\n\nModuleNode.body = StatListNode(__init__.pxd:17:0)\nStatListNode.stats[41] = StatListNode(__init__.pxd:842:5                                                                                                               )\nStatListNode.stats[0] = CFuncDefNode(__init__.pxd:842:5,\n    args = [...]/4,\n    inline_in_pxd = True,\n    modifiers = [                                                                                                               ...]/1,\n    visibility = \'private\')\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", l                                                                                                               ine 180, in Cython.Compiler.Visitor.TreeVisitor._visit\n  File "/home/ivan/anaconda3/envs/open-mmlab/lib/python3.7/site-packag                                                                                                               es/Cython/Compiler/ParseTreeTransforms.py", line 2215, in visit_FuncDefNode\n    node.body = node.body.analyse_expressions(nod                                                                                                               e.local_scope)\n  File "/home/ivan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436,                                                                                                                in analyse_expressions\n    for stat in self.stats]\n  File "/home/ivan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/                                                                                                               Cython/Compiler/Nodes.py", line 436, in <listcomp>\n    for stat in self.stats]\n  File "/home/ivan/anaconda3/envs/open-mmlab/                                                                                                               lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6675, in analyse_expressions\n    self.item = self.item.coerce_to(                                                                                                               self.target.type, env)\n  File "/home/ivan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py"                                                                                                               , line 952, in coerce_to\n    src = PyTypeTestNode(src, dst_type, env)\n  File "/home/ivan/anaconda3/envs/open-mmlab/lib/pytho                                                                                                               n3.7/site-packages/Cython/Compiler/ExprNodes.py", line 12999, in __init__\n    assert dst_type.is_extension_type or dst_type.i                                                                                                               s_builtin_type, "PyTypeTest on non extension type"\nAssertionError: PyTypeTest on non extension type', AssertionError('PyTypeT                                                                                                               est on non extension type'), <traceback object at 0x7f3ac4220748>)
```

**Comment by ivder** [comment]
Solved by upgrading conda to the latest version
`conda update -n base -c defaults conda`

**Comment by sunpeng981712364** [comment]
> Solved by upgrading conda to the latest version
> `conda update -n base -c defaults conda`

It works! Thanks a lot!

**Comment by zihaozhang9** [comment]
I still get an error when I reinstall [nccl](https://github.com/open-mmlab/mmdetection/issues/1025#issuecomment-532548138). Then use the `conda update -n base -c defaults conda` command, the compilation is successful. 
Thank you very much.

**Comment by zhaohui-yang** [comment]
> Solved by upgrading conda to the latest version
> `conda update -n base -c defaults conda`

Works fine!
