### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#3047]
**Describe the bug**
I train ResNeXt model with myself dataset. I found there has a relationship between the DCN and samples_per_gpu and workers_per_gpu. Related configuration as below segment:

model = dict(
    pretrained=None, #'open-mmlab://resnext50_64x4d',
    backbone=dict(
        type='ResNeXt',
        depth=50,
        groups=32,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        plugins=[
            dict(
                cfg=dict(type='ContextBlock', ratio=1. / 16),
                stages=(False, True, True, True),
                position='after_conv3')
        ],
        style='pytorch',
        dcn=dict(type='DCN', deformable_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True)))
data = dict(samples_per_gpu=2, workers_per_gpu=2)

When I set data = dict(samples_per_gpu=2, workers_per_gpu=2), the error will happened:
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

But if I set data = dict(samples_per_gpu=1, workers_per_gpu=1). Then the training procedure is normal.

Additional information:
1. I already use myself dataset for training mask-rcnn, cascade-mask-rcnn, HTC with resnet.
2. In my config, if I delete DCN part, then I can set dict(samples_per_gpu=2, workers_per_gpu=2). So I think the DCN part cause this issue.
3. I found a similar issue in https://github.com/open-mmlab/mmdetection/issues/2661. But I check the latest mmdetection/mmdet/ops/dcn/src/cuda/deform_conv_cuda.cpp, line 427 don't change, still is:  at::Tensor gradOutputBuffer = at::zeros_like(gradOutput);

So could you please check why samples_per_gpu and workers_per_gpu value affect the DCN function.

**Environment**
------------------------------------------------------------
sys.platform: linux
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0: GeForce RTX 2070
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0
OpenCV: 3.4.2
MMCV: 0.5.1
MMDetection: 2.0.0+6603790
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.2
------------------------------------------------------------
**Error traceback**
work_dir='work_dirs/htc/20200618'
gpu_ids=range(0, 1)
loading annotations into memory...
Done (t=0.34s)
creating index...
index created!
2020-06-16 16:55:34,237 - mmdet - INFO - Start running, host: ceyang@ceyang-lenovoserver, work_dir: /home/ceyang/mmdetection/work_dirs/htc/20200618
2020-06-16 16:55:34,237 - mmdet - INFO - workflow: [('train', 1)], max: 200 epochs
Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 155, in main
    meta=meta)
  File "/home/ceyang/mmdetection/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ceyang/.conda/envs/dt2/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ceyang/.conda/envs/dt2/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 289, in train
    self.call_hook('after_train_iter')
  File "/home/ceyang/.conda/envs/dt2/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ceyang/.conda/envs/dt2/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/hooks/optimizer.py", line 21, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/ceyang/.conda/envs/dt2/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ceyang/.conda/envs/dt2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by yhcao6** [comment]
It seems you are training with HTC but modifying the backbone. I tested with the following config on COCO dataset:
```
_base_ = './htc_r50_fpn_1x_coco.py'

model = dict(
    pretrained=None,  #'open-mmlab://resnext50_64x4d',
    backbone=dict(
        type='ResNeXt',
        depth=50,
        groups=32,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        plugins=[
            dict(
                cfg=dict(type='ContextBlock', ratio=1. / 16),
                stages=(False, True, True, True),
                position='after_conv3')
        ],
        style='pytorch',
        dcn=dict(type='DCN', deformable_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True)))
```
The program can run without error. Are you using a similar config? If yes, could you have a try on COCO to see if it will report the same error?

**Comment by minghigh** [comment]
RuntimeError: view size is not compatible with input tensor's size and stride

- mmcv: 0.5.9
- mmdet: 2.0.0+c77ccbb
- pytorch: 1.5.0

config: 

`
config_path = ''
_base_ = [
    config_path + '_base_/models/faster_rcnn_r50_fpn.py',
    config_path + './_base_/datasets/coco_detection.py',
    config_path + './_base_/schedules/schedule_1x.py', config_path + './_base_/default_runtime.py'
]

# dataset
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1500, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1500, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

dataset_type = 'CocoDataset'
data_root = '/home/daofu/zhongjianke/data/coco/'
classes = ('沙眼类', '划伤类', '磕碰类', '污渍类')

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'train.json',
        img_prefix=data_root + 'images/',
        classes=classes,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'valid.json',
        img_prefix=data_root + 'images',
        classes=classes,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'valid.json',
        img_prefix=data_root + 'images/',
        classes=classes,
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')

# model
train_cfg = dict(rcnn=dict(sampler=dict(type='OHEMSampler')))
test_cfg = dict(
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='soft_nms', iou_thr=0.5),
        max_per_img=100))

# ??
model = dict(
    pretrained='open-mmlab://resnext101_32x4d',
    backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=32,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        style='pytorch'),
    roi_head=dict(bbox_head=dict(num_classes=len(classes))))


model = dict(
    pretrained='open-mmlab://resnext101_32x4d',
    backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=32,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        style='pytorch',
        dcn=dict(type='DCN', deformable_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True)),
        roi_head=dict(bbox_head=dict(num_classes=len(classes))))

# schedule + runtime
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
total_epochs = 12
load_from = 'faster_rcnn_x101_32x4d_fpn_1x_coco_20200203-cff10310.pth'
work_dir = ''

`

error:

`
/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of addcmul is deprecated:
        addcmul(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
        addcmul(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out)
Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 155, in main
    meta=meta)
  File "/home/daofu/mmdetection/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 384, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 290, in train
    self.call_hook('after_train_iter')
  File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 21, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
`

**Comment by drahmad89** [comment]
I have exactly the same error

**Comment by JazzeYoung** [comment]
Have exactly the same, is anything to do with the random preprocessing?

**Comment by PressEtoRace** [comment]
I also have the same error. Has anyone solved the problem?

**Comment by RulinShao** [comment]
Same error. Any solution?

**Comment by ktw361** [comment]
Found the same problem, resolved by replacing each `view` function with `reshape` in mmdet/ops/dcn/src/deform_conv_cuda.cpp:
```sed -i 's/view/reshape/g' mmdet/ops/dcn/src/deform_conv_cuda.cpp```

**Comment by v-qjqs** [comment]
> I also have this problem
> 
> * mmcv: 0.5.9
> * mmdet: 2.0.0+c77ccbb
> * pytorch: 1.5.0
> 
> config:
> 
> ```
> config_path = ''
> _base_ = [
>     config_path + '_base_/models/faster_rcnn_r50_fpn.py',
>     config_path + './_base_/datasets/coco_detection.py',
>     config_path + './_base_/schedules/schedule_1x.py', config_path + './_base_/default_runtime.py'
> ]
> 
> # dataset
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations', with_bbox=True),
>     dict(type='Resize', img_scale=(1500, 800), keep_ratio=True),
>     dict(type='RandomFlip', flip_ratio=0.5),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(1500, 800),
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='Pad', size_divisor=32),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> 
> dataset_type = 'CocoDataset'
> data_root = ''
> classes = ('')
> 
> data = dict(
>     samples_per_gpu=2,
>     workers_per_gpu=2,
>     train=dict(
>         type=dataset_type,
>         ann_file=data_root + 'train.json',
>         img_prefix=data_root + 'images/',
>         classes=classes,
>         pipeline=train_pipeline),
>     val=dict(
>         type=dataset_type,
>         ann_file=data_root + 'valid.json',
>         img_prefix=data_root + 'images',
>         classes=classes,
>         pipeline=test_pipeline),
>     test=dict(
>         type=dataset_type,
>         ann_file=data_root + 'valid.json',
>         img_prefix=data_root + 'images/',
>         classes=classes,
>         pipeline=test_pipeline))
> evaluation = dict(interval=1, metric='bbox')
> 
> # model
> train_cfg = dict(rcnn=dict(sampler=dict(type='OHEMSampler')))
> test_cfg = dict(
>     rcnn=dict(
>         score_thr=0.05,
>         nms=dict(type='soft_nms', iou_thr=0.5),
>         max_per_img=100))
> 
> model = dict(
>     pretrained='open-mmlab://resnext101_32x4d',
>     backbone=dict(
>         type='ResNeXt',
>         depth=101,
>         groups=32,
>         base_width=4,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         style='pytorch',
>         dcn=dict(type='DCN', deformable_groups=1, fallback_on_stride=False),
>         stage_with_dcn=(False, True, True, True)),
>         roi_head=dict(bbox_head=dict(num_classes=len(classes))))
> 
> # schedule + runtime
> optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
> total_epochs = 12
> load_from = 'faster_rcnn_x101_32x4d_fpn_1x_coco_20200203-cff10310.pth'
> work_dir = ''
> ```
> 
> error:
> 
> ```
> /opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of addcmul is deprecated:
>         addcmul(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
> Consider using one of the following signatures instead:
>         addcmul(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out)
> Traceback (most recent call last):
>   File "tools/train.py", line 159, in <module>
>     main()
>   File "tools/train.py", line 155, in main
>     meta=meta)
>   File "/home/daofu/mmdetection/mmdet/apis/train.py", line 165, in train_detector
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 384, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 290, in train
>     self.call_hook('after_train_iter')
>   File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 245, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 21, in after_train_iter
>     runner.outputs['loss'].backward()
>   File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/daofu/miniconda3/envs/open-mmlab2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
> ```


Hi, my experiments with pytorch version 1.5 and mmcv-full version 1.1.5 didn't raise above error, and it's normal. Could you please update your mmcv version?

**Comment by v-qjqs** [comment]
> Found the same problem, resolved by replacing each `view` function with `reshape` in mmdet/ops/dcn/src/deform_conv_cuda.cpp:
> `sed -i 's/view/reshape/g' mmdet/ops/dcn/src/deform_conv_cuda.cpp`

Hi, I wonder there the error still exists with the new updated mmdetection and mmcv? Since this [PR](https://github.com/open-mmlab/mmdetection/pull/4325) had moved mmdet.ops to mmcv.

**Comment by ktw361** [comment]
> > Found the same problem, resolved by replacing each `view` function with `reshape` in mmdet/ops/dcn/src/deform_conv_cuda.cpp:
> > `sed -i 's/view/reshape/g' mmdet/ops/dcn/src/deform_conv_cuda.cpp`
> 
> Hi, I wonder whether the error still exists with the new updated mmdetection and mmcv?
> Since this [PR](https://github.com/open-mmlab/mmdetection/pull/4325) had moved mmdet.ops to mmcv.

Hi, I didn't test new version of mmdetection. The code in my case has been fixed.

**Comment by laisimiao** [comment]
> Found the same problem, resolved by replacing each `view` function with `reshape` in mmdet/ops/dcn/src/deform_conv_cuda.cpp: `sed -i 's/view/reshape/g' mmdet/ops/dcn/src/deform_conv_cuda.cpp`

This can fix my situation
