### ISSUE TITLE
Unexpected result : On training the model using cascade_rcnn and gfl.

### ISSUE THREAD

**Issue by Siddhijain16** [open-mmlab/mmdetection#3890]
Hi,
I am using cascade_rcnn_hrnetv2p_w32_20e_coco.py and gfl_r50_fpn_1x_coco.py to train a model on custom dataset .
My dataset images is of type " abc.pdf.jpg ". After training I'm getting this type of result  in both cases .Is this because of my image format or something else ? Please suggest.

[cascade_rcnn_hrnetv2p_w32_20e_coco.zip](https://github.com/open-mmlab/mmdetection/files/5331750/cascade_rcnn_hrnetv2p_w32_20e_coco.zip)
[gfl_r50_fpn_1x_coco.zip](https://github.com/open-mmlab/mmdetection/files/5331751/gfl_r50_fpn_1x_coco.zip)

cascade_rcnn result

![image_2020_10_05T12_22_47_207Z](https://user-images.githubusercontent.com/46879959/95165207-2c6b9100-07c9-11eb-9629-573abf8454e0.png)

gfl result

![image_2020_10_06T05_44_41_078Z](https://user-images.githubusercontent.com/46879959/95165229-33929f00-07c9-11eb-88ad-6eac6b71cb9d.png)

**Comment by ZwwWayne** [comment]
Hi @Siddhijain16 ,
What is your version of MMDet? If you modify the classes of COCO dataset through config in an old version, the test data will be filtered and the eval AP becomes zero. This bug should have been fixed by https://github.com/open-mmlab/mmdetection/pull/3695. You can try to evaluate the model with the newest mmdetection and the evaluation results should be normal.

**Comment by Siddhijain16** [comment]
I am using the latest version of MMDet but still getting the same results .

**Comment by ZwwWayne** [comment]
Then I have no idea about that.
