### ISSUE TITLE
RuntimeError: operation does not have an identity.

### ISSUE THREAD

**Issue by SmellyBear333** [open-mmlab/mmdetection#5402]
**Describe the bug**
I have trained the DetectorRS model for a while , but during the time , it happened "RuntimeError: operation does not have an identity.".

**Reproduction**
Before i met this error, I was running this command :"nohup python tools/train.py ./configs/detectors/detectors_htc_r50_1x_coco.py --work-dir ./detectors_train_test_res"
I haven not modified your code, and the dataset is coco2017.

**environment**
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2060 SUPER
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.2
MMCV: 1.3.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.13.0+a8c681d

**Error traceback**
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/home/ubuntu/Desktop/work/Users/smellycat/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ubuntu/Desktop/work/Users/smellycat/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/Desktop/work/Users/smellycat/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ubuntu/Desktop/work/Users/smellycat/mmdetection/mmdet/models/detectors/two_stage.py", line 135, in forward_train
    proposal_cfg=proposal_cfg)
  File "/home/ubuntu/Desktop/work/Users/smellycat/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 58, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 182, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/Desktop/work/Users/smellycat/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 580, in get_bboxes
    scale_factors, cfg, rescale)
  File "/home/ubuntu/Desktop/work/Users/smellycat/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 185, in _get_bboxes
    cfg.nms)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 268, in batched_nms
    max_coordinate = boxes.max()
RuntimeError: operation does not have an identity.

what should I do if I want to continue running ? please tell me more details (I am totally a newbie:( 
thank you!

**Comment by BIGWangYuDong** [comment]
This error seems boxes value is empty.

**Comment by BIGWangYuDong** [comment]
@SmellyBear333 
What command or script did you run?

Did you make any modifications on the code or config? Did you understand what you have modified?

What dataset did you use?

**Comment by SmellyBear333** [comment]
> @SmellyBear333
> What command or script did you run?
> 
> Did you make any modifications on the code or config? Did you understand what you have modified?
> 
> What dataset did you use?

I ran this command:nohup python tools/train.py ./configs/detectors/detectors_htc_r50_1x_coco.py --work-dir ./detectors_train_test_res"

I have not modified your code, and the dataset is coco2017.(the one contains stuffthingmaps)







> This error seems boxes value is empty.

yes,so yesterday i tried to modified the 155 lines "nms=dict(type='nms', iou_threshold=0.7)," into "nms=dict(type='nms', iou_threshold=0.4),",which in the "mmdetection/configs/htc/htc.without_semantic_r50_fpn_1x_coco.py" . then it continue running for about 20hours,but today in the morning, it say "RuntimeError: operation does not have an identity."again and it stopped again :(

**Comment by BIGWangYuDong** [comment]
It seems the same error, you can refer to #5211

**Comment by SmellyBear333** [comment]
> It seems the same error, you can refer to #5211

Thanks for your advise! then what could i do before @hhaAndroid fixed it in the DetectoRS ?

**Comment by SmellyBear333** [comment]
> @SmellyBear333
> What command or script did you run?
> 
> Did you make any modifications on the code or config? Did you understand what you have modified?
> 
> What dataset did you use?

oh,sorry I fogot that I modified the configs "lr=0.02"into"lr=0.01",which is in the "mmdetection/configs/_base_/schedules/schedule_1x.py". 
and I modified "samples_per_gpu=2,workers_per_gpu=2" into"samples_per_gpu=1,workers_per_gpu=1",which is in the line 32 and 33 in "configs/_base_/datasets/coco_detection.py".
These modification just for take down the batchsize and learning rate to match.
Looking forward to your reply ! Thank u !

**Comment by BIGWangYuDong** [comment]
@SmellyBear333 maybe you can upgrade MMDetection and MMCV first. I think that we have already fixed this bug.

**Comment by SmellyBear333** [comment]
> @SmellyBear333 maybe you can upgrade MMDetection and MMCV first. I think that we have already fixed this bug.
I git pull the latest mmdetection code , and I trained again ,but in this morning ,it turns out "RuntimeError: operation does not have an identity."again.maybe @hhaAndroid have not fixed this bug . pleaseeeee help me get out of this Error :( thanks a lot

**Comment by SmellyBear333** [comment]
> @SmellyBear333 maybe you can upgrade MMDetection and MMCV first. I think that we have already fixed this bug.

I git pull the latest mmdetection code , and I trained again ,but in this morning ,it turns out "RuntimeError: operation does not have an identity."again.maybe @hhaAndroid have not fixed this bug . pleaseeeee help me get out of this Error :( thanks a lot

**Comment by BIGWangYuDong** [comment]
Please make sure you have updated MMdet and MMCV

**Comment by SmellyBear333** [comment]
> Please make sure you have updated MMdet and MMCV

According to running the command"python mmdet/utils/collect_env.py",my MMdet version is **2.13.0**+a8c681d and my MMCV version is **1.3.3**.
Are these the latest versions ? If not, How could I update them ?
