### ISSUE TITLE
[Bug] Wrong type np.bool in mmdet/datasets/transforms/loading.py

### ISSUE THREAD

**Issue by chofchof** [open-mmlab/mmdetection#9557]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

`mmdet/datasets/transforms/loading.py` of 3.x brach contains two wrong type `np.bool` as follows.

> Line #273 & #359: `results['gt_ignore_flags'] = np.array(gt_ignore_flags, dtype=np.bool)`

It should be replaced by `np.bool_`.

### Reproduces the problem - code sample

`demo/image_demo.py`

### Reproduces the problem - command or script

```shell
python demo/image_demo.py demo/demo.jpg yolov3_mobilenetv2_8xb24-320-300e_coco.py yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth --device cuda --out-file result.jpg
```

### Reproduces the problem - error message

```
AttributeError: module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?
```

**Comment by RangiLyu** [comment]
This bug has been fixed in https://github.com/open-mmlab/mmdetection/pull/9537

**Comment by Billccx** [comment]
> This bug has been fixed in #9537
Could you please explain in detail? I still failed to run this demo.

**Comment by Billccx** [comment]
By installing "mmdet==3.0.0rc2", the problem solved. However version rc3~rc5 still have the problem.

**Comment by Billccx** [comment]
想借此提一个建议，您们的项目非常优秀，文档也很好，但是各版本之间的关系似乎十分混乱，而且每个版本的文档都不太相同，导致想运行demo都要花费一定的努力。个人观感仅供参考。
